@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
Class Game
Game -> "2..4" Players
Players --> "1" Account
Players -> "1" Piece
DieCup"1" <- Game
DieCup --> "2" Die
Game --> "1" Board
Board --> "24" Field
Field --> "16"ProportyField
Field --> "4"ChanceField
Field --> "4"NoActionField

Class Board
Class Field
Class ProportyField
Class ChanceField
Class NoActionField

Class Field
Field : #int fieldName
Field : landetOn ()
Field : getName ()
Field : field ()

Class ChanceField
ChanceField : #Field
ChanceField : MoveToStart ()
ChanceField : Move5Fields ()
ChanceField : MoveToSP ()

Class Board
Board : makeField ()
Board : toString ()

Class Game

Class NoActionField
NoActionField : # Field
NoActionField : doNothing()

Class ProportyField
ProportyField : - int buyPrice
ProportyField : - int rent
ProportyField : - String player
ProportyField : PayRent ()
ProportyField : SetOwner ()
ProportyField : BuyField ()

Class DieCup
DieCup : - int dieSum
DieCup : - Die die1,die2
DieCup : + Shake () {
DieCup : die1.roll ()
DieCup : die2.roll () }
DieCup : getDieSum () {mangler}


Class Die
Die : - int facevalue
Die : - int maxFacevalue
Die : + Die (int max)
Die : + roll ()
Die : + getFacevalue ()

Class Players
Players : - bankAccount bank
Players : - String name
Players : - int playerAccount
Players : - int player ()
Players : - Piece ()

Class Piece
Piece : - int location
Piece : - String color
Piece : + getLocation ()
Piece : + addLocation (int dieSum)
Piece : + setLocation (int field)
Piece : + String toString ()

Class Account
Account : - int balance
Account : + account (int inbalance)
Account : + getBalance ()
Account : + addBalance (int amount)

@enduml