@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
Class Game
Game -> "2..4" Players
Players --> "1" Account
Players -> "1" Piece
DieCup"1" <- Game
DieCup --> "1" Die
Game --> "1" Board
Board --> "24" Field
Field --> "16"ProportyField
Field --> "4"ChanceField
Field --> "4"NoActionField

Class Board
Class Field
Class ProportyField
Class ChanceField
Class NoActionField

abstract class Field
Field : - String fieldName
Field : + landetOn ()
Field : + field ()

Class ChanceField
ChanceField : + landetOn (Player player)
ChanceField : + ChanceField (String name)

Class Board
Board :  Field[] fields
Board : + makeField ()
Board : + toString ()

Class Game
Game : + makeField()
Game : + createPlayers (int numberOfPlayers)
Game : + takeTurn (int player)
Game : + chooseWinner ()

Class NoActionField
NoActionField : + NoActionField ()
NoActionField : + landetOn()


Class ProportyField
ProportyField : - int buyPrice
ProportyField : - int rent
ProportyField : - String playerName
ProportyField : - Player owner
ProportyField : + ProportyField (Player owner, String ownerName, String name, int price, int rent)
ProportyField : + int getBuyPrice ()
ProportyField : + String toString ()


Class DieCup
DieCup : - int dieSum
DieCup : - maxFacevalue
DieCup : + Shake ()
DieCup : + dieCup (int dieSides)


Class Die
Die : - int facevalue
Die : - int maxFacevalue
Die : + Die (int dieSides)
Die : + roll ()

Class Players
Players : - String name
Players : - int playerNumber
Players : - int playerCounter
Players : + Players (String name)
Players : + toString ()

Class Piece
Piece : - int location
Piece : - String color
Piece : + addLocation (int dieSum)
Piece : + String toString ()

Class Account
Account : - int balance
Account : + account ()
Account : + payRent (Account player)
Account : + addBalance (int amount)
Account : + toString()

@enduml