@startuml
'https://plantuml.com/sequence-diagram

autonumber

Player -> System: StartGame()
Player -> System: Game.language()
Player -> System: Player[] players = new Player[int NoOfPlayers]




@enduml