@startuml
'https://plantuml.com/use-case-diagram
skinparam actorStyle awesome

Player as Foo1

package Monopoly{
    usecase "Play game" as UC1
    usecase "Start game" as UC2
    usecase "Take turn" as UC3

}
left to right direction
Foo1 --> UC1
UC1 ..> UC2 :includes
UC1 ..> UC3 : includes



@enduml