@startuml
'https://plantuml.com/use-case-diagram
skinparam actorStyle awesome
[<<actor>>\nSystem] as Foo
Player as Foo1
[<<actor>>\nRandomCalculator] as Foo2
package Game{
    usecase "ryk brik" as UC1
    usecase "slå terning" as UC2
    usecase "land på felt" as UC3
    usecase "vælg spillere" as UC5
    usecase "skift tur" as UC6
}
left to right direction
Foo1 --> UC5
Foo1 -> UC2

UC1 <- Foo
UC6 <- Foo
UC3 <-- Foo
UC2 <-- Foo2


@enduml